version: 2
updates:
  # Rust dependencies
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      rust:
        patterns:
          - "*"

  # Node dependencies
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      node:
        patterns:
          - "*"

  # CI dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      ci:
        patterns:
          - "*"
