version: 2
updates:
  # Node dependencies
  - package-ecosystem: npm
    directories:
      - /
      - /examples/desktop-clock
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      all:
        patterns:
          - "*"

  # Cargo dependencies
  - package-ecosystem: cargo
    directories:
      - /
      - /examples/desktop-clock/src-tauri
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      all:
        patterns:
          - "*"

  # GitHub Actions dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
