[package]
name = "desktop-clock"
version = "0.0.1"
description = ""
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-rc.7", features = [] }

[dependencies]
tauri = { version = "2.0.0-rc.8", features = [ "tray-icon", "macos-private-api"] }
tauri-plugin-desktop-underlay = { path = "../../../" }
